/**
 * PaymentPage — Guest scans a PromptPay QR code to pay for their service request.
 *
 * Route: /guest/payment/:requestId
 *
 * Flow:
 *   1. Load request details (verify it is in SP_ACCEPTED or PENDING_PAYMENT state)
 *   2. Call trpc.requests.initiatePayment to generate a QR charge
 *   3. Display QR code + amount + expiry countdown
 *   4. Poll trpc.requests.pollPayment every 3 s
 *   5. On PAID → navigate to /guest/track/:refNo with success banner
 *   6. On FAILED / expired → show retry button
 *
 * Note: The QR is generated by the stub payment gateway (server/stubPaymentGateway.ts).
 * Replace with real Omise SDK once credentials are available.
 */

import { useState, useEffect, useRef, useCallback } from "react";
import {
  Box, Typography, Card, CardContent, Button, Chip,
  CircularProgress, Alert, LinearProgress, Divider,
} from "@mui/material";
import {
  CheckCircle, Clock, RefreshCw, AlertTriangle, CreditCard,
  QrCode, ShieldCheck, Zap,
} from "lucide-react";
import { toast } from "sonner";
import { useLocation, useParams } from "wouter";
import GuestLayout from "@/layouts/GuestLayout";
import { trpc } from "@/lib/trpc";

// ── Helpers ──────────────────────────────────────────────────────────────────

function formatTHB(amount: number): string {
  return `฿${amount.toLocaleString("th-TH", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function useCountdown(targetIso: string | null): string {
  const [remaining, setRemaining] = useState("");

  useEffect(() => {
    if (!targetIso) return;
    const target = new Date(targetIso).getTime();

    const tick = () => {
      const diff = target - Date.now();
      if (diff <= 0) { setRemaining("Expired"); return; }
      const m = Math.floor(diff / 60000);
      const s = Math.floor((diff % 60000) / 1000);
      setRemaining(`${m}:${s.toString().padStart(2, "0")}`);
    };

    tick();
    const id = setInterval(tick, 1000);
    return () => clearInterval(id);
  }, [targetIso]);

  return remaining;
}

// ── Component ─────────────────────────────────────────────────────────────────

type PaymentState = "loading" | "generating" | "pending" | "paid" | "failed" | "error";

export default function PaymentPage() {
  const [, navigate] = useLocation();
  const params = useParams<{ requestId: string }>();

  const sessionId = localStorage.getItem("pa_session_id") ?? "guest";

  // ── Request data ─────────────────────────────────────────────────────────
  const [requestParams] = useState(() => ({ requestId: params.requestId }));
  const requestQuery = trpc.requests.getRequest.useQuery(requestParams, {
    retry: 1,
    staleTime: 10_000,
  });

  // ── Payment state ─────────────────────────────────────────────────────────
  const [paymentState, setPaymentState] = useState<PaymentState>("loading");
  const [paymentId, setPaymentId] = useState<string | null>(null);
  const [qrDataUrl, setQrDataUrl] = useState<string | null>(null);
  const [qrPayload, setQrPayload] = useState<string | null>(null);
  const [amount, setAmount] = useState<number>(0);
  const [expiresAt, setExpiresAt] = useState<string | null>(null);
  const [errorMsg, setErrorMsg] = useState("");
  const [paidAt, setPaidAt] = useState<string | null>(null);
  const [refNo, setRefNo] = useState<string | null>(null);

  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // ── tRPC mutations ────────────────────────────────────────────────────────
  const [simulating, setSimulating] = useState(false);

  const simulatePaymentMutation = trpc.requests.simulatePayment.useMutation({
    onSuccess: (data) => {
      setPaymentState("paid");
      setPaidAt(data.paidAt ?? null);
      toast.success("Payment simulated! Redirecting…");
      if (refNo) {
        setTimeout(() => navigate(`/guest/track/${refNo}`), 2500);
      }
    },
    onError: (err) => {
      toast.error(err.message ?? "Simulation failed");
    },
    onSettled: () => setSimulating(false),
  });

  const handleSimulatePayment = useCallback(() => {
    if (!paymentId || simulating) return;
    setSimulating(true);
    simulatePaymentMutation.mutate({ paymentId, sessionId });
  }, [paymentId, sessionId, simulating]);

  const initiatePaymentMutation = trpc.requests.initiatePayment.useMutation({
    onSuccess: (data) => {
      setPaymentId(data.paymentId);
      setQrDataUrl(data.qrDataUrl);
      setQrPayload(data.qrPayload);
      setAmount(data.amount);
      setExpiresAt(data.expiresAt);
      setPaymentState("pending");
    },
    onError: (err) => {
      setErrorMsg(err.message ?? "Could not generate payment QR. Please try again.");
      setPaymentState("error");
    },
  });

  // ── Poll payment status ───────────────────────────────────────────────────
  const [pollParams] = useState<{ paymentId: string; sessionId: string } | null>(null);
  const pollQuery = trpc.requests.pollPayment.useQuery(
    { paymentId: paymentId ?? "", sessionId },
    {
      enabled: !!paymentId && paymentState === "pending",
      refetchInterval: 3000,
      staleTime: 0,
    }
  );

  useEffect(() => {
    if (!pollQuery.data) return;
    const { status, paidAt: paid } = pollQuery.data;

    if (status === "PAID") {
      setPaymentState("paid");
      setPaidAt(paid ?? null);
      // Navigate to tracking after 2.5 s
      if (refNo) {
        setTimeout(() => navigate(`/guest/track/${refNo}`), 2500);
      }
    } else if (status === "FAILED") {
      setPaymentState("failed");
      setErrorMsg("Payment failed. Please try again.");
    }
  }, [pollQuery.data, refNo, navigate]);

  // ── Derive refNo from request ─────────────────────────────────────────────
  useEffect(() => {
    if (requestQuery.data?.request?.requestNumber) {
      setRefNo(requestQuery.data.request.requestNumber);
    }
  }, [requestQuery.data]);

  // ── Auto-initiate payment once request is loaded ──────────────────────────
  useEffect(() => {
    if (paymentState !== "loading") return;
    if (!requestQuery.data) return;

    const { request, payment } = requestQuery.data;

    // If there's already a pending payment, restore it
    if (payment && payment.status === "PENDING" && payment.qrDataUrl) {
      setPaymentId(payment.id);
      setQrDataUrl(payment.qrDataUrl);
      setQrPayload(payment.qrPayload ?? "");
      setAmount(parseFloat(payment.amount));
      setExpiresAt(payment.expiresAt?.toISOString() ?? null);
      setPaymentState("pending");
      return;
    }

    // If already paid
    if (payment && payment.status === "PAID") {
      setPaymentState("paid");
      setPaidAt(payment.paidAt?.toISOString() ?? null);
      return;
    }

    // Initiate new payment
    const payableStates = ["SP_ACCEPTED", "PENDING_PAYMENT"];
    if (!payableStates.includes(request.status)) {
      setErrorMsg(`Cannot pay from state "${request.status}". The service provider has not accepted yet.`);
      setPaymentState("error");
      return;
    }

    setPaymentState("generating");
    initiatePaymentMutation.mutate({
      requestId: params.requestId,
      sessionId,
    });
  }, [requestQuery.data, paymentState]);

  // ── Retry ─────────────────────────────────────────────────────────────────
  const handleRetry = useCallback(() => {
    setPaymentState("generating");
    setErrorMsg("");
    setPaymentId(null);
    setQrDataUrl(null);
    initiatePaymentMutation.mutate({
      requestId: params.requestId,
      sessionId,
    });
  }, [params.requestId, sessionId]);

  const countdown = useCountdown(expiresAt);

  // ── Render ────────────────────────────────────────────────────────────────

  if (requestQuery.isLoading || paymentState === "loading") {
    return (
      <GuestLayout propertyName="Payment">
        <Box sx={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 3, py: 6 }}>
          <CircularProgress size={48} sx={{ color: "#1A1A1A" }} />
          <Typography variant="body2" sx={{ color: "#737373" }}>
            Loading payment details…
          </Typography>
        </Box>
      </GuestLayout>
    );
  }

  if (requestQuery.isError) {
    return (
      <GuestLayout propertyName="Payment">
        <Alert severity="error" sx={{ borderRadius: 1.5, mb: 2 }}>
          Could not load request details. Please go back and try again.
        </Alert>
        <Button variant="outlined" size="small" onClick={() => window.history.back()}
          sx={{ textTransform: "none" }}>
          Go Back
        </Button>
      </GuestLayout>
    );
  }

  const request = requestQuery.data?.request;

  // ── PAID state ────────────────────────────────────────────────────────────
  if (paymentState === "paid") {
    return (
      <GuestLayout propertyName="Payment Confirmed">
        <Box sx={{ textAlign: "center", py: 4 }}>
          <Box sx={{
            width: 80, height: 80, borderRadius: "50%", bgcolor: "#F0FDF4",
            mx: "auto", mb: 2, display: "flex", alignItems: "center", justifyContent: "center",
          }}>
            <CheckCircle size={40} color="#16A34A" />
          </Box>
          <Typography variant="h5" sx={{ fontWeight: 700, color: "#171717", mb: 0.5 }}>
            Payment Confirmed!
          </Typography>
          <Typography variant="body2" sx={{ color: "#737373", mb: 3 }}>
            {paidAt ? `Paid at ${new Date(paidAt).toLocaleTimeString("th-TH")}` : "Your payment was successful."}
          </Typography>

          <Card variant="outlined" sx={{ borderRadius: 2, mb: 3, textAlign: "left" }}>
            <CardContent sx={{ py: 2 }}>
              <Typography variant="caption" sx={{ color: "#A3A3A3", textTransform: "uppercase", letterSpacing: 0.5 }}>
                Amount Paid
              </Typography>
              <Typography variant="h4" sx={{ fontWeight: 700, color: "#16A34A" }}>
                {formatTHB(amount)}
              </Typography>
              {refNo && (
                <Typography variant="caption" sx={{ color: "#737373" }}>
                  Ref: {refNo}
                </Typography>
              )}
            </CardContent>
          </Card>

          <Typography variant="body2" sx={{ color: "#737373", mb: 2 }}>
            Redirecting to request tracking…
          </Typography>
          <LinearProgress sx={{ borderRadius: 1, bgcolor: "#E5E7EB" }} />

          {refNo && (
            <Button
              variant="contained"
              fullWidth
              sx={{ mt: 3, textTransform: "none", borderRadius: 1.5, bgcolor: "#1A1A1A" }}
              onClick={() => navigate(`/guest/track/${refNo}`)}
            >
              Track My Request
            </Button>
          )}
        </Box>
      </GuestLayout>
    );
  }

  // ── ERROR state ───────────────────────────────────────────────────────────
  if (paymentState === "error" || paymentState === "failed") {
    return (
      <GuestLayout propertyName="Payment">
        <Box sx={{ textAlign: "center", py: 4 }}>
          <Box sx={{
            width: 80, height: 80, borderRadius: "50%", bgcolor: "#FEF2F2",
            mx: "auto", mb: 2, display: "flex", alignItems: "center", justifyContent: "center",
          }}>
            <AlertTriangle size={40} color="#DC2626" />
          </Box>
          <Typography variant="h6" sx={{ fontWeight: 700, color: "#171717", mb: 1 }}>
            Payment Issue
          </Typography>
          <Typography variant="body2" sx={{ color: "#737373", mb: 3 }}>
            {errorMsg || "Something went wrong with your payment."}
          </Typography>

          {paymentState === "failed" && (
            <Button
              variant="contained"
              fullWidth
              startIcon={<RefreshCw size={16} />}
              onClick={handleRetry}
              sx={{ textTransform: "none", borderRadius: 1.5, bgcolor: "#1A1A1A", mb: 2 }}
            >
              Try Again
            </Button>
          )}

          <Button
            variant="outlined"
            fullWidth
            onClick={() => window.history.back()}
            sx={{ textTransform: "none", borderRadius: 1.5 }}
          >
            Go Back
          </Button>
        </Box>
      </GuestLayout>
    );
  }

  // ── GENERATING state ──────────────────────────────────────────────────────
  if (paymentState === "generating") {
    return (
      <GuestLayout propertyName="Payment">
        <Box sx={{ display: "flex", flexDirection: "column", alignItems: "center", gap: 3, py: 6 }}>
          <CircularProgress size={48} sx={{ color: "#1A1A1A" }} />
          <Typography variant="body2" sx={{ color: "#737373" }}>
            Generating QR code…
          </Typography>
        </Box>
      </GuestLayout>
    );
  }

  // ── PENDING state (main QR display) ──────────────────────────────────────
  return (
    <GuestLayout propertyName="Scan to Pay">
      {/* Header */}
      <Box sx={{ textAlign: "center", mb: 3 }}>
        <Box sx={{
          width: 56, height: 56, borderRadius: "50%", bgcolor: "#F0F9FF",
          mx: "auto", mb: 1.5, display: "flex", alignItems: "center", justifyContent: "center",
        }}>
          <QrCode size={28} color="#0369A1" />
        </Box>
        <Typography variant="h6" sx={{ fontWeight: 700, color: "#171717" }}>
          Scan QR to Pay
        </Typography>
        <Typography variant="body2" sx={{ color: "#737373", mt: 0.5 }}>
          Use any Thai banking app to scan
        </Typography>
      </Box>

      {/* Amount card */}
      <Card variant="outlined" sx={{ borderRadius: 2, mb: 2, bgcolor: "#FAFAFA" }}>
        <CardContent sx={{ py: 2, textAlign: "center" }}>
          <Typography variant="caption" sx={{ color: "#A3A3A3", textTransform: "uppercase", letterSpacing: 0.5 }}>
            Total Amount
          </Typography>
          <Typography variant="h3" sx={{ fontWeight: 800, color: "#171717", my: 0.5 }}>
            {formatTHB(amount)}
          </Typography>
          {refNo && (
            <Chip
              label={`Ref: ${refNo}`}
              size="small"
              sx={{ bgcolor: "#F3F4F6", color: "#6B7280", fontSize: "0.7rem" }}
            />
          )}
        </CardContent>
      </Card>

      {/* QR Code */}
      <Card variant="outlined" sx={{ borderRadius: 2, mb: 2 }}>
        <CardContent sx={{ display: "flex", flexDirection: "column", alignItems: "center", py: 3 }}>
          {qrDataUrl ? (
            <Box
              component="img"
              src={qrDataUrl}
              alt="PromptPay QR Code"
              sx={{
                width: 220, height: 240, display: "block",
                border: "1px solid #E5E7EB", borderRadius: 1,
              }}
            />
          ) : (
            <Box sx={{
              width: 220, height: 240, display: "flex", alignItems: "center", justifyContent: "center",
              border: "2px dashed #E5E7EB", borderRadius: 1,
            }}>
              <CircularProgress size={32} />
            </Box>
          )}

          {/* Expiry countdown */}
          <Box sx={{ display: "flex", alignItems: "center", gap: 0.75, mt: 2 }}>
            <Clock size={14} color="#D97706" />
            <Typography variant="caption" sx={{ color: "#D97706", fontWeight: 600 }}>
              Expires in {countdown || "…"}
            </Typography>
          </Box>
        </CardContent>
      </Card>

      {/* Polling indicator */}
      <Box sx={{ mb: 2 }}>
        <Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 0.75 }}>
          <CircularProgress size={14} sx={{ color: "#6B7280" }} />
          <Typography variant="caption" sx={{ color: "#6B7280" }}>
            Waiting for payment confirmation…
          </Typography>
        </Box>
        <LinearProgress
          variant="indeterminate"
          sx={{ borderRadius: 1, height: 3, bgcolor: "#F3F4F6", "& .MuiLinearProgress-bar": { bgcolor: "#0369A1" } }}
        />
      </Box>

      {/* Instructions */}
      <Card variant="outlined" sx={{ borderRadius: 2, mb: 2, bgcolor: "#F0F9FF", borderColor: "#BAE6FD" }}>
        <CardContent sx={{ py: 1.5 }}>
          <Typography variant="caption" sx={{ fontWeight: 600, color: "#0369A1", display: "block", mb: 0.5 }}>
            How to pay:
          </Typography>
          {[
            "Open your banking app (Krungthai, SCB, KBank, etc.)",
            "Tap \"Scan QR\" or \"PromptPay\"",
            "Scan the QR code above",
            "Confirm the amount and complete payment",
          ].map((step, i) => (
            <Typography key={i} variant="caption" sx={{ color: "#0C4A6E", display: "block", mb: 0.25 }}>
              {i + 1}. {step}
            </Typography>
          ))}
        </CardContent>
      </Card>

      {/* Security badge */}
      <Box sx={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 0.75, py: 1 }}>
        <ShieldCheck size={14} color="#16A34A" />
        <Typography variant="caption" sx={{ color: "#6B7280" }}>
          Secured by Omise · PromptPay
        </Typography>
      </Box>

      {/* Stub notice + Simulate button */}
      <Alert severity="info" sx={{ borderRadius: 1.5, mt: 1, fontSize: "0.7rem", mb: 1.5 }}>
        <strong>Demo mode:</strong> This is a stub QR. Payment will auto-confirm in ~15 seconds.
      </Alert>

      {/* Simulate Payment button — stub only, for faster testing */}
      <Button
        variant="outlined"
        fullWidth
        startIcon={simulating ? <CircularProgress size={14} /> : <Zap size={14} />}
        onClick={handleSimulatePayment}
        disabled={simulating || !paymentId}
        sx={{
          textTransform: "none",
          borderRadius: 1.5,
          borderColor: "#FCD34D",
          color: "#92400E",
          bgcolor: "#FFFBEB",
          fontSize: "0.75rem",
          "&:hover": { bgcolor: "#FEF3C7", borderColor: "#F59E0B" },
        }}
      >
        {simulating ? "Simulating…" : "⚡ Simulate Payment (Demo Only)"}
      </Button>
    </GuestLayout>
  );
}
